version: "3.7"

services:
    model:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: model
        volumes:
            - ../out:/app/out
            - ../cache:/app/.cache
        environment:
            - LOW_MEMORY=1
            - PORT=8080
        ports:
            - "0.0.0.0:5343:8080"
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
#   interface:
