import "./globals.css";

import { cn } from "@/lib/utils";
import { Poppins } from "next/font/google";

import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
    adjustFontFallback: true,
    display: "swap",
    preload: true,
    fallback: ["sans-serif"],
    weight: [
        "400", // Regular
        "700", // Bold
    ],
    style: "normal",
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "note-buddy",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "min-h-screen font-sans antialiased bg-gray-900 text-gray-100 flex flex-col",
                    poppins.variable
                )}
            >
                {children}
                <Toaster />
            </body>
        </html>
    );
}
