import "./globals.css";

import { cn } from "@/lib/utils";
import { Poppins } from "next/font/google";

import type { Metadata } from "next";
const poppins = Poppins({
    adjustFontFallback: true,
    display: "swap",
    preload: true,
    fallback: ["sans-serif"],
    weight: [
        "400", // Regular
        "700", // Bold
    ],
    style: "normal",
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("min-h-screen bg-background font-sans antialiased", poppins.variable)}>{children}</body>
        </html>
    );
}
